#!/bin/bash
# Specify jobname:
#SBATCH --job-name=MyJob
# Specify the number of nodes and the number of CPU's (tasks) per node:
#SBATCH --nodes=1
#SBATCH --ntasks=40
# Specify account. 
#SBATCH --account=nn9136k
# The maximum time allowed for the job, in hh:mm:ss
#SBATCH --time=24:00:00
# Maximum memory allowed per cpu
#SBATCH --mem-per-cpu=4G
# export I_MPI_ADJUST_RUDECE=3
OMPI_OPT="--blind-to core"
PROG=vasp
#done

## Set up job environment    
module purge
module load intel/2022b

## Run command 
srun /cluster/home/josephpa/cBN/bin/vasp


exit 0
